name: simple_tools_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  # State management
  # https://pub.dev/packages/flutter_bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  # Util functions
  # https://pub.dev/packages/collection
  collection: ^1.17.2
  # IOS icons
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.2
  # Http request hanlder
  # https://pub.dev/packages/dio
  dio: ^5.3.3
  # Object compare
  # https://pub.dev/packages/equatable
  equatable: ^2.0.5
  # Firebase
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  # Responsive UI elements
  # https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.0
  # Svg reader
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.9
  # Dart functional programming
  # https://pub.dev/packages/fpdart
  fpdart: ^1.1.0
  # Dependency injection
  # https://pub.dev/packages/get_it
  get_it: ^7.6.4
  # App routes
  # https://pub.dev/packages/go_router
  go_router: ^12.1.1
  # Pick image
  # https://pub.dev/packages/image_picker
  image_picker: ^1.0.4
  # Formatter
  # https://pub.dev/packages/intl
  intl: ^0.18.1
  # Hanlde permission in app
  # https://pub.dev/packages/permission_handler
  permission_handler: ^11.0.1
  # Async extends
  # https://pub.dev/packages/rxdart
  rxdart: ^0.27.7
  # Store data locally
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.2

dev_dependencies:
  # Generate code
  build_runner: ^2.4.6
  # Test
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  mocktail: ^1.0.1

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
