name: simple_tools_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  get_it: ^7.6.4
  go_router: ^12.1.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  permission_handler: ^11.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2

dev_dependencies:
  # Test
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
      - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
